Notebook/Notebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('note.urls')),
]

Notebook/note/urls.py
from django.urls import path
from .views import NoteListView, NoteCreateView, NoteUpdateView, NoteDeleteView, NoteDetailView

app_name = 'note'
urlpatterns = [
    path('', NoteListView.as_view(), name='note-list'),
    path('create/', NoteCreateView.as_view(), name='note-create'),
    path('update/<int:pk>/', NoteUpdateView.as_view(), name='note-update'),
    path('delete/<int:pk>/', NoteDeleteView.as_view(), name='note-delete'),
    path('detail/<int:pk>/', NoteDetailView.as_view(), name='note-detail'),

]

Notebook/note/models.py
from django.db import models


class Note(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

Notebook/note/forms.py
from dataclasses import field
from email.policy import default
import re
from turtle import title
from django import forms
from .models import Note


class NoteForm(forms.ModelForm):
    title = forms.CharField(required=False)

    class Meta:
        model = Note
        fields = ('title', 'content')

    # If there is no title, it puts the first 7 characters of the text in the title.
    def clean(self):
        clean_data = super().clean()
        if not clean_data['title']:
            clean_data['title'] = clean_data['content'][:7] + '...'
        return clean_data

Notebook/note/views.py
from django.views.generic import edit, list, UpdateView, DetailView
from django.urls import reverse
from .models import Note
from .forms import NoteForm


class NoteListView(list.ListView):
    template_name = 'index.html'
    model = Note
    queryset = Note.objects.order_by('-updated_at')[:10]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = NoteForm()
        return context


class NoteCreateView(edit.CreateView):
    template_name = 'index.html'
    form_class = NoteForm

    def get_success_url(self):
        return reverse('note:note-list')


class NoteUpdateView(UpdateView):
    template_name = 'index.html'
    form_class = NoteForm
    queryset = Note.objects.all()

    def get_success_url(self):
        return reverse('note:note-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['update'] = 'update'
        context['object_list'] = Note.objects.order_by('-updated_at')[:10]
        return context


class NoteDeleteView(edit.DeleteView):
    template_name = 'index.html'
    model = Note

    def get_success_url(self):
        return reverse('note:note-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['delete'] = 'Are you sure?'
        context['form'] = NoteForm()
        context['object_list'] = Note.objects.order_by('-updated_at')[:10]
        return context


class NoteDetailView(DetailView):
    template_name = 'index.html'
    model = Note

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['detail'] = 'detail'
        context['form'] = NoteForm()
        context['object_list'] = Note.objects.order_by('-updated_at')[:10]
        return context

Notebook/note/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Notebook</title>
    <style>
        #container {
            width: 90%;
            height: 800px;
            background-color: aquamarine;
            margin: auto;
        }

        .box {
            width: 50%;
            height: 400px;
            float: left;
            padding: 20px;
            box-sizing: border-box;
        }

        li {
            font-size: 22px;
        }
    </style>
</head>

<body>
    <div id='container'>
        <div class="box" style="background-color: blueviolet;">
            <h1>Your last notes:</h1>
            <ul>
                {% for note in object_list %}
                <li><a href="{% url 'note:note-detail' note.pk %}">{{ note.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="box" style="background-color: brown;">
            {% if update %}
            <form action="{% url 'note:note-update' note.pk %}" method="post">
                {% csrf_token%}
                {{ form.as_p }}<br>
                <input type="submit" value="edit">
            </form>
            {% else %}
            <form action="{% url 'note:note-create' %}" method="post">
                {% csrf_token%}
                {{ form.as_p }}<br>
                <input type="submit" value="Save">
            </form>
            {% endif %}
        </div>
        <div class="box" style="background-color: burlywood;">
            {% if detail %}
            <h2>{{note.title}}</h2>
            <p>{{note.content}}</p>
            <a href="{% url 'note:note-update' note.pk %}"><button type="submit">Edit</button></a>
            <a href="{% url 'note:note-delete' note.pk %}"><button type="submit">Delete</button></a>
            {% endif %}
            {% if delete %}
            <form action="{% url 'note:note-delete' note.pk %}" method="post">{% csrf_token %}
                {{delete}}
                <input type="submit" value="yes">
                <a href="{% url 'note:note-list' %}"><button type="button">no</button></a>
            </form>
            {% endif %}
        </div>
        <div class="box" style="background-color: cadetblue;"></div>
    </div>

</body>

</html>